### ISSUE TITLE
[INS-2101] [Feature] User can hover some button or tag to have tooltip for better information

### ISSUE THREAD

**Issue by EiffelFly** [instill-ai/community#392]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill Base

### Is your Proposal Related to a Problem?

Some of the buttons in pipeline builder is a bit hard to understand, but it's also hard to give them an proper instruction under current design.

### Describe Your Proposed Solution

We can provide the tooltip when user hover the button

<sub>[INS-2101](https://linear.app/instill-ai/issue/INS-2101/[feature]-user-can-hover-some-button-or-tag-to-have-tooltip-for-better)</sub>

**Comment by anurag629** [comment]
@EiffelFly, I want to work on this issue. Can you please provide more details?

**Comment by harshsoni7** [comment]
> @EiffelFly, I want to work on this issue. Can you please provide more details?

Hi Anurag! Absolutely, we’re thrilled about your interest in our project! :rocket: Here’s the [Contributing Guideline](https://github.com/instill-ai/base/blob/main/.github/CONTRIBUTING.md) for Instill Base to get you started on your journey! Don’t forget to [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) your pull request to the corresponding issue, and after your PR gets merged, please complete this [form](https://forms.gle/2r91a7ChMLVnWLm37) to claim your well-deserved points! If you ever have any questions or need a hand along the way, don’t hesitate to drop a message in this thread or hop into our [Discord](https://discord.gg/sevxWsqpGh). We will officially assign this issue to you once you submit the pull request. Happy contributing! :blush::star2:

**Comment by anurag629** [comment]
> > @EiffelFly, I want to work on this issue. Can you please provide more details?
> 
> Hi Anurag! Absolutely, we’re thrilled about your interest in our project! 🚀 Here’s the [Contributing Guideline](https://github.com/instill-ai/base/blob/main/.github/CONTRIBUTING.md) for Instill Base to get you started on your journey! Don’t forget to [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) your pull request to the corresponding issue, and after your PR gets merged, please complete this [form](https://forms.gle/2r91a7ChMLVnWLm37) to claim your well-deserved points! If you ever have any questions or need a hand along the way, don’t hesitate to drop a message in this thread or hop into our [Discord](https://discord.gg/sevxWsqpGh). We will officially assign this issue to you once you submit the pull request. Happy contributing! 😊🌟

@harshsoni7 Please assign this to me.
