### ISSUE TITLE
[INS-2163] [Bug] In dark mode the search bar placeholder color not visible

### ISSUE THREAD

**Issue by iamnamananand996** [instill-ai/community#414]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill Base

### Describe the Bug

![CleanShot 2023-09-26 at 01 35 55@2x](https://github.com/instill-ai/community/assets/31537362/bd49da98-f1ad-40e7-a63a-fecec4a5a870)

![CleanShot 2023-09-26 at 01 36 17@2x](https://github.com/instill-ai/community/assets/31537362/42210fae-5cc8-4fc0-a30a-dfb22d4230c7)

### Steps to Reproduce

Switch to the dark mode.

### Actual Result

search bar placeholder color should be visible

### Technical Details

```markdown
- **Project version**:
- **Service name**:
- **Service name**:
- **OS**:
- **Browser**:
```

<sub>[INS-2163](https://linear.app/instill-ai/issue/INS-2163/[bug]-in-dark-mode-the-search-bar-placeholder-color-not-visible)</sub>

**Comment by sajdakabir** [comment]
hay @iamnamananand996 I would like to work on this issue. can you assign it to me?

**Comment by EiffelFly** [comment]
@sajdakabir Thanks for your will of contributing our project, we are really appreciated it, please go ahead and file the PR here

**Comment by Gagantomar17** [comment]
Hey I would like to work on this issue and fix it. Can you please assign this to me ..

**Comment by harshsoni7** [comment]
Hi @Gagantomar17, thank you so much for your interest! Since @sajdakabir came first, we've assigned it to him.

But please feel free to check out any of our other issues :)

**Comment by harshsoni7** [comment]
@sajdakabir Thanks!

@iamnamananand996, please review the PR. Thank you.

**Comment by harshsoni7** [comment]
Hi @sajdakabir, since your PR has been merged, please complete this [form](https://forms.gle/2r91a7ChMLVnWLm37) to claim your well-deserved points! Thank you!

**Comment by ShihChun-H** [comment]
@all-contributors please add @sajdakabir for bug fix.

**Comment by ShihChun-H** [comment]
@all-contributors please add @sajdakabir for bug fix.

**Comment by ShihChun-H** [comment]
@all-contributors please add @sajdakabir for code
