### ISSUE TITLE
[INS-2203] [Improvement] JSON Operator to take multiple input paths

### ISSUE THREAD

**Issue by praharshjain** [instill-ai/community#426]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

Yes, currently the JSON operator takes a JSON string, and a path pattern as input and returns the value at the given path, if found. If a user needs multiple values from the same JSON, they need one operator instance for each value.

### Describe Your Proposed Improvement

We can enhance the JSON operator to take a list of paths (instead of just one), and return a list of values (respectively).

### Highlight the Benefits

A single operator can be used to extract multiple values from the same JSON.

<sub>[INS-2203](https://linear.app/instill-ai/issue/INS-2203/[improvement]-json-operator-to-take-multiple-input-paths)</sub>

**Comment by itssiddhantjain** [comment]
Hello @praharshjain , please assign this issue to me as i already worked on this kind of problem in past and has a great experience.

**Comment by itssiddhantjain** [comment]
Hey @praharshjain I have sent you a PR, kindly review and merge it under hacktoberfest.

**Comment by harshsoni7** [comment]
@itssiddhantjain Thank you!

> Hey @praharshjain I have sent you a PR, kindly review and merge it under hacktoberfest.

@donch1989 Can you please review the PR?

**Comment by itssiddhantjain** [comment]
> @itssiddhantjain Thank you!
> 
> > Hey @praharshjain I have sent you a PR, kindly review and merge it under hacktoberfest.
> 
> @donch1989 Can you please review the PR?
Is it merged ?

**Comment by donch1989** [comment]
Hi @itssiddhantjain ,

Thank you very much for your contributions.

However, we regret to inform you that there might have been a misunderstanding. This issue requires implementation in Golang within the [operator](https://github.com/instill-ai/operator) repository. We will improve our contribution guidelines to prevent this from happening again.

Additionally, after our internal discussions, we have decided to cancel this feature request. We have other open issues available for contributions, welcome for your contribution.

Thanks.
