### ISSUE TITLE
[INS-2326] [Feature] support metadata in Pinecone connector

### ISSUE THREAD

**Issue by donch1989** [instill-ai/community#444]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

We need to support metadata in Pinecone connector.

### Describe Your Proposed Solution

1. add metadata in Pinecone connector
2. support free-form metadata data flow setting in Console

### Highlight the Benefits

for basic RAG, to save original text in Pinecone

### Anything Else?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [INS-2326](https://linear.app/instill-ai/issue/INS-2326/[feature]-support-metadata-in-pinecone-connector)</sub>

**Comment by donch1989** [comment]
@xiaofei.du 
So this task will assign to @jvalles ?

**Comment by xiaofei-du** [comment]
Yeah. @jvalles, can you take care of this task?

**Comment by donch1989** [comment]
Hi @jvalles ,
I'll be AFK later. How about we sync at 8am London time tomorrow?

**Comment by xiaofei-du** [comment]
@leo.chen is our expert for Pinecone If you need insights.

**Comment by donch1989** [comment]
Hi @leo.chen,
The meeting will be short and focus on the connector implementation. About the use-cases, I think we can arrange another meeting later this week.

**Comment by donch1989** [comment]
Currently, the Pinecone connector involves two tasks: `TASK_UPSERT` and `TASK_QUERY`, both of which require integration with Pinecone metadata.

I propose breaking down this task into two stages:

## **Stage 1:**

**Goal:** Store metadata along with the vector to retrieve corresponding metadata during vector queries.

**Tasks:**

1. **TASK_UPSERT:** Store metadata during upsert. Refer to the documentation: [Upsert Documentation](https://docs.pinecone.io/reference/upsert).
2. **TASK_QUERY:** When conducting vector queries, obtain the corresponding metadata using `includeMetadata: true`. Refer to the documentation: [Query Documentation](https://docs.pinecone.io/reference/query).

## **Stage 2:**

**Goal:** Utilize metadata to refine vector queries.

**Tasks:**

1. **TASK_QUERY:** Enhance vector queries by adding additional `filter` for metadata to limit query results. Refer to the documentation: [Query Documentation](https://docs.pinecone.io/reference/query).

**Comment by donch1989** [comment]
A simple development guideline:

1. Go to pinecone.io, create an account, and set up an index with a dimension of `1536` (matching the dimension of the OpenAI embedding model).
2. Create a pipeline using the example recipe below. This should enable you to extract the text's embedding and write it into Pinecone.
3. I've initiated a [branch](https://github.com/instill-ai/connector/tree/jvalles/ins-2326) for the `TASK_UPSERT` JSON-schema changes. The `metadata` field should be found on Console. You can try to implement how to write `metadata` to Pinecone.
4. Do the similar changes for the `TASK_QUERY` to read the metadata from Pinecone

```
{
  "version": "v1beta",
  "components": [
    {
      "id": "start",
      "resource_name": "",
      "configuration": {
        "metadata": {
          "id": {
            "instillFormat": "string",
            "title": "id",
            "type": "string"
          },
          "text": {
            "instillFormat": "string",
            "title": "text",
            "type": "string"
          }
        }
      },
      "definition_name": "operator-definitions/start"
    },
    {
      "id": "end",
      "resource_name": "",
      "configuration": {
        "input": {
          "count": "{pinecone_0.output.upserted_count}"
        },
        "metadata": {
          "count": {
            "title": "count"
          }
        }
      },
      "definition_name": "operator-definitions/end"
    },
    {
      "id": "pinecone_0",
      "resource_name": "users/admin/connectors/pinecone-test",
      "configuration": {
        "input": {
          "id": "{start.id}",
          "values": "{openai_0.output.embedding}"
        },
        "task": "TASK_UPSERT"
      },
      "definition_name": "connector-definitions/pinecone"
    },
    {
      "id": "openai_0",
      "resource_name": "users/admin/connectors/openai",
      "configuration": {
        "input": {
          "model": "text-embedding-ada-002",
          "text": "{start.text}"
        },
        "task": "TASK_TEXT_EMBEDDINGS"
      },
      "definition_name": "connector-definitions/openai"
    }
  ]
}
```

**Comment by donch1989** [comment]
The missing line is a bug on Console, we will fix that.

> ***My question is***: do we want to show the metadata (or the resulting vector) in the `end` component (i.e. do we want to modify the output schema)? On the one hand it shows the available data, but my fear is that for complex metadata / high-dimensional vectors the output will be unclear.

Yes, we need to show it on the end operator, the complex content is a improvement issue for Console. (We had a thought that we will show this kind of complex content in a pop-up dialog and have dedicated UI for them).

**Comment by donch1989** [comment]
> {pinecone_0.output.matches.metadata.color}

This one is the scope of map reduce operator, the operator can iterate the array and combine the results. We'll start to work on this operator in this Sprint. I think we can finish it before Feb.

> 1. As the TASK_UPSERT metadata input currently can only come from the output of another component, will there be a way to modify the metadata key name of this component output in the future?
>
> * This could be useful in cases where different data sources might have different field names but the same meaning (e.g., ‘source’, ‘url’, ‘link’, ‘website’, …). So the Filter can be easier to apply across different data sources.
>
> 1. Also, will there be a way to filter which output attributes should be uploaded as metadata to Pinecone?
>
> * Some field values from the component output might be noisy, confidential, or empty, and users might not want to upload them to Pinecone.

We are working on refactoring the reference syntax [INS-2629](https://linear.app/instill-ai/issue/INS-2629/refactor-the-component-reference-schema). After this done, we will continue to implement a JSON operator that can fulfill your requirement. Basically, the goal is that you can assemble the JSON from different upstream values. The ETA will be Sprint 27.

**Comment by donch1989** [comment]
@jvalles not sure if you have time to implement the jq operator. I don't have much bandwidth in Sprint 27, 28

**Comment by donch1989** [comment]
Oh.. wait, you were talking about putting `jq` directly in the input value. 

Currently we want to make the component input value syntax as simple as possible. Integrating the `jq` directly in the input value might be too advanced.
I think we can have a `jq` operator first, then we can consider whether to integrate it into input value or not in the future.

**Comment by donch1989** [comment]
We have a similar case. Originally, we supported two syntax **variable reference** `{}` and **Liquid** string literal `{{}}` in component input.

But after few months of experiments, we found that it is too difficult to educate the users, and the Console will be hard to implement the smart hint. So we decided to remove **Liquid** support and keep only **variable reference** in component input, and we will make the **Liquid** as a standalone operator.

**Comment by donch1989** [comment]
> I have some tasks assigned in the backlog but I don't have much visibility beyond this sprint. I'll raise this point before next sprint starts and if it has enough priority I can tackle it.

Yeah, I think the priority is lower than other tasks.
