### ISSUE TITLE
[Bug][Docs] Deployment docs for base seem broken 

### ISSUE THREAD

**Issue by syedzubeen** [instill-ai/community#452]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill Website

### Describe the Bug

Tried accessing docs to learn more about base deployment but the docs link seems broken right now and needs to be fixed.

URL: https://www.instill.tech/docs/base/deployment/overview

![image](https://github.com/instill-ai/community/assets/14253061/b556e7ed-a979-483a-9008-7faca50cfc56)

### Steps to Reproduce

NA

### Expected Behavior

The doc link should work as expected and not return with an internal server error.

### Technical Details

- **Project version**:
- **Service name**:
- **Service version**:
- **OS**:
- **Browser**:

**Comment by ShihChun-H** [comment]
Hi @syedzubeen,

Is this the page you are looking for?
URL: https://www.instill.tech/docs/base/v1.0.0/deployment/overview

Could you please let us know where you found the URL you provided? We need to update the URL to the correct one.

**Comment by syedzubeen** [comment]
Hey @ShihChun-H !

Yup, that's what I was looking for. Here is the one that needs fixing with some others as well. 😄 

- **URL**: https://www.instill.tech/docs/core/v1.0.0/getting-started

**Broken Link text on page:** documentation

![image](https://github.com/instill-ai/community/assets/14253061/c1ad7e9e-e102-4a9b-bbc9-743957dd1d88)


- **URL**: https://www.instill.tech/docs/cloud/v1.0.0/welcome 

**Broken Link text on page**: Guidlines

![image](https://github.com/instill-ai/community/assets/14253061/e50ad886-fbaa-4139-a9e1-6c8078f52f92)


- **URL**: https://www.instill.tech/docs/vdp/v1.0.0/getting-started


**Broken Link text on page**: Connectors

![image](https://github.com/instill-ai/community/assets/14253061/03a65009-bf0d-4d89-b5bd-d2ac44f7bed7)


- **URL**: https://www.instill.tech/docs/core/v1.0.0/getting-started

**Broken Link text on page:** how to deploy Model

![image](https://github.com/instill-ai/community/assets/14253061/ab36c01e-7038-41ce-8463-60dfb5af9ccc)

**Comment by ShihChun-H** [comment]
Hi @syedzubeen, 

Thank you for collecting all the broken links. We will update the documents as soon as possible!
Since those links are currently broken, did it affect your ability to accomplish what you wanted?

Shih-Chun

**Comment by syedzubeen** [comment]
I'd say yes, cause at that time I was building my setup and was getting an error related to base and when turning to docs I came accross this broken link. But now with the link you provided I'll retry fixing my issues.
