### ISSUE TITLE
[INS-2516] [Improvement] refactor instillFormat in start operator

### ISSUE THREAD

**Issue by donch1989** [instill-ai/community#475]
### Is There an Existing Issue for This?

* [X] I have searched the existing issues

### Project

Instill VDP

### Is your Proposal Related to a Problem?

* We want to use instillFormat in start operator configuration to make the format definition consistent across all components

### Describe Your Proposed Improvement

* use `instillFormat` in start operator to config data fields
* Currently, the format is like this

```
"metadata": {
  "input": {
    "title": "Input",
    "type": "TYPE"
  },
  "input_array": {
    "title": "Input Array",
    "type": "TYPE_array"
  }
}
```

* We'll change to this

```
"metadata": {
  "input": {
    "title": "Input",
    "type": "TYPE"
    "instillAcceptFormats": ["INSTILL_FORMAT"]
  },
  "input_array": {
    "title": "Input Array",
    "type": "array",
    "instillAcceptFormats": ["array:INSTILL_FORMAT"]
    "items": {
      "type": "type",
    }
  }
}
```

| type | instillFormat | can_be_array | UI |
| -- | -- | -- | -- |
| bool | bool | false | ? |
| integer | integer | true | text field |
| number | number | true | text field |
| string | string | true | text field |
| string | image/\* | true | file uploader with image preview |
| string | audio/\* | true | file uploader with audio preview |
| string | video/\* | true | file uploader with video preview |
| string | \*/\* | true | file uploader |
|  |  |  |  |

### Highlight the Benefits

*No response*

### Anything Else?

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [INS-2516](https://linear.app/instill-ai/issue/INS-2516/[improvement]-refactor-instillformat-in-start-operator)</sub>

**Comment by donch1989** [comment]
@pochun.chiu ,
please take a look at this

**Comment by EiffelFly** [comment]
I am thinking totally replacing "type" with "instillFormat"

What do you think

**Comment by donch1989** [comment]
But how do we annotate it is a array?

**Comment by EiffelFly** [comment]
At the first though, I am thinking let use the items as a identifier. But on the second though, this will deviate from auto-form. I think we can directly use your proposal

**Comment by donch1989** [comment]
BTW, @pochun.chiu 

Since we are going to have RAG showcases, we'll need to find a way to allow users to upload files.

Originally, in addition to the audio and image user interfaces we already have, I thought about having two separate user interfaces for text file ( `text/*` *) and other types of file (like* `application/pdf`). However, upon further consideration, having two different user interfaces may not be very user-friendly, as users may not be familiar with the distinctions between `text/*` *and* `application*`

In fact, I'm thinking whether we should just have a single file user interface that can be used for images, videos, audio, text files, and other types of files.

**Comment by donch1989** [comment]
cc @pinglin @xiaofei.du

**Comment by donch1989** [comment]
I propose that we implement Option 1 first. We can ensure forward compatibility by using `installAcceptFormats`, allowing us to upgrade to Option 3 easily in the future.

**Comment by EiffelFly** [comment]
> Personally, I think Option 1 might be the most user-friendly choice. Option 3 offers the most fine-grained control, but it seems too advanced at the current stage.

I agree.

And this need to pair with smart hint too to have a good user-experience.

I have a question, what will be the usecase that we need to accept any kind of files?

**Comment by donch1989** [comment]
For example, we might have a document extractor. It will take a file as an input and extract its content to texts. And the document extractor can accept many kinds of input files e.g. `html`, `csv`, `pdf`, `docx`,`pptx` …etc

**Comment by EiffelFly** [comment]
Got it then I support option1 and then we can think of more advanced solution after beta 🤝

**Comment by xiaofei-du** [comment]
* Option 1:
  * image, audio, video have their own type/instillFormat in start operator like current version
    * `image/*`, `audio/*`, `video/*`
  * we have another generic instillFormat `*/*` for images, videos, audio, text files, and other types of files. 

If we have `*/*`, why do we still need the other types? @donch1989

**Comment by donch1989** [comment]
> If we have `*/*`, why do we still need the other types?

I think it is for the UI purpose. For `*/*`, it will only be a file upload/download UI on Console. But for `image/*`, `audio/*`, `video/*`, we can show dedicated UI for them.
