### ISSUE TITLE
[Improvement] Minor mistake on Documentation

### ISSUE THREAD

**Issue by ShihChun-H** [instill-ai/community#481]
### Is There an Existing Issue for This?

- [X] I have searched the existing issues

### Project

Instill Website

### Is your Proposal Related to a Problem?

The numbers on[ Instill Model Documentation](https://www.instill.tech/docs/v0.4.1-alpha/vdp/ai-connectors/instill-model) is wrong.

<img width="970" alt="Snipaste_2023-11-09_14-43-56" src="https://github.com/instill-ai/community/assets/143982976/018010f2-fe4a-4472-9f44-537c611a98cf">

### Describe Your Proposed Improvement

Update the numbers

**Comment by iamnamananand996** [comment]
Hi @xiaofei-du, please help me to understand this issue, what I should update here

we just need to change the `5` --> `2` or some docs content is missing ?.

**Comment by ShihChun-H** [comment]
@iamnamananand996, You can just tag me. 
At the top, it says 1 and 6. 
At the bottom, it says 1 and 5. 
I suppose you just need to change the bottom "5" to "6".
